#!/bin/bash

if [ $# -ne 1 ]; then
    echo "$0: usage is:"
    echo "$0 [debian_version_tag]"
    echo "example: gh_build bookworm-20240904"
    echo "Debian base Docker image tags: https://hub.docker.com/_/debian/tags"
    exit 1
fi

VERSION="$1"

gh workflow run build-image \
   -F version="${VERSION}"
