name: build-image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Debian base Docker image tag (https://hub.docker.com/_/debian/tags)'
        required: true
        default: 'buster-20230109'

env:
  IMAGENAME: debian-secff
  VERSION: ${{ github.event.inputs.version || vars.VERSION }}

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: context
          build-args: |
            VERSION=${{ env.VERSION }}
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGENAME }}:${{ steps.date.outputs.date }}.${{ github.run_number }}
